# DOT PRODUCT IN NUMPY

Specifically, there are two rules to consider in dot product in python:
#### 1. If both vector “A” and vector “B” are 1-dimensional arrays, it is an inner product of vector (without complex conjugation).
#### 2. If both vector “A” and vector “B” are 2-dimensional arrays, it is a matrix multiplication.
You can only multiply two matrices if the number of columns of the first matrix is equal to the number of rows of the second matrix.




# Matrix product is calculated manually

In [2]:
# We can then go ahead and multiply 2 matrices, here is an example of a 1*1 matrix “A” multiply with 1*1 matrix “B”.
# That is: A * B = C


 **Question**

$$ A = \begin{bmatrix}-1\\ 2\\ 3 \end{bmatrix} B = \begin{bmatrix}0 \\ 2 \\ 1 \end{bmatrix}=7 $$

**SOLUTION**

**STEP 1:**
$$ \begin{bmatrix}(-1*0)+(2*2)+(3*1) \end{bmatrix} $$


**STEP 2:**
$$
\begin{bmatrix}0+4+3\end{bmatrix} $$

**FINAL ANSWER**

$$
\begin{bmatrix}7\end{bmatrix} $$


In [4]:
# Firstly, import the Numpy package in your workspace and then create a 2D matrix as discussed in 
# the example above or any other matrix structure you want to try it out with. Then create a vector 
# ensuring the number of rows being equal to the number of columns in the matrix.
# You can then use the “dot()” method in the matrix and vector. It will return the result vector for you as shown.
# You can check out the entire notebook and play around with the code using.
# Let’s code them using Numpy:


In [5]:
import numpy as np
# we are importing the library


In [6]:
a = np. array ([[-1, 2, 3]])
b = np. array([[-0, 2, 1]])
# we are using vector “a” and vector “b”

In [7]:
print(a)

[[-1  2  3]]


In [8]:
print(b)

[[0 2 1]]


In [9]:
np.inner(a, b)
# we are finding the inner product

array([[7]])

# And additional work

In [10]:
import numpy as np

In [16]:
A = np.array([1,2])
B = np.array([3,4])

In [12]:
print(A)

[1 2]


In [13]:
print(B)

[3 4]


In [14]:
#the first thing we can try if you dont know anything about numpy is, use the direct defination
#that is, we can multiply the arrays together and sum up the result
#let start by creating the variable "dot" and initialize that to "zero"


In [18]:
dot = 0
for  e, f in zip(A, B):
    dot += e*f
dot


11