# python from the begining

## There are four main datatypes in python
### 1. int = means whole number
### 2. string = means characters
### 3. float = means decimal
### 4. Boolean = mean True or Fals.

# Arithmetic operetor's:

#### Arithemic operetor's: are use to perform arithetic on number(literals or variables).

## Examples with Addition operator(calculations)

In [1]:
a = 10
b = 20
c = a+b
print(c)

30


In [2]:
a = '10'
b = '20'
c = a+b
print(c)

1020


In [3]:
a = 'Bo'
b = 'ok'
c = a+b
print(c)

Book


In [1]:
a = 'Fo'
b = 'day'
c = a+b
print(c)

Foday


## Examples with Addition operator(using input)

In [2]:
a = int(input("Enter a value"))
b = int(input("Enter b value"))
c = a+b
print("The sum of ",a, "and",b, "is",c);

Enter a value4
Enter b value7
The sum of  4 and 7 is 11


In [2]:
x = int(input("Enter x value"))
y = int(input("Enter y value"))
z = x+y
print("The sum of ",x, "and",y, "is",z);

Enter x value2
Enter y value3
The sum of  2 and 3 is 5


## Examples with Multiplication operator

In [2]:
x = 30
y = 10
z = x*y
print(z)

300


In [5]:
a = 10
b = 20
c = a*b
print(c)

200


## Examples with Multiplication operator(using input)

In [7]:
a = int(input("Enter a value"))
b = int(input("Enter b value"))
c = a*b
print("The sum of ",a, "and",b, "is",c);

Enter a value2
Enter b value4
The sum of  2 and 4 is 8


In [8]:
x = int(input("Enter x value"))
y = int(input("Enter y value"))
z = x*y
print("The sum of ",x, "and",y, "is",z);

Enter x value4
Enter y value4
The sum of  4 and 4 is 16


## Examples with Substraction operator

In [3]:
a = 50
b = 20
c = a-b
print(c)

30


In [4]:
x = 30
y = 10
z = x-y
print(z)

20


## Examples with substraction operator(using input)

In [5]:
a = int(input("Enter a value"))
b = int(input("Enter b value"))
c = a-b
print("The sum of ",a, "and",b, "is",c);

Enter a value20
Enter b value10
The sum of  20 and 10 is 10


In [6]:
x = int(input("Enter x value"))
y = int(input("Enter y value"))
z = x-y
print("The sum of ",x, "and",y, "is",z);

Enter x value20
Enter y value5
The sum of  20 and 5 is 15


## Examples with division operator

In [7]:
a = 50
b = 2
c = a/b
print(c)

25.0


In [8]:
x = 300
y = 10
z = x/y
print(z)

30.0


## Examples with division operator(using input)

In [9]:
a = int(input("Enter a value"))
b = int(input("Enter b value"))
c = a/b
print("The sum of ",a, "and",b, "is",c);

Enter a value20
Enter b value2
The sum of  20 and 2 is 10.0


In [25]:
x = int(input("Enter x value"))
y = int(input("Enter y value"))
z = x/y
print("The sum of ",x, "and",y, "is",z);

Enter x value2
Enter y value8
The sum of  2 and 8 is 0.25


## Examples with module operator

In [11]:
a = 50
b = 2
c = a%b
print(c)

0


In [12]:
x = 30
y = 12
z = x%y
print(z)

6


## Examples with module operator(useing input)

In [13]:
a = int(input("Enter a value"))
b = int(input("Enter b value"))
c = a%b
print("The sum of ",a, "and",b, "is",c);

Enter a value10
Enter b value4
The sum of  10 and 4 is 2


In [14]:
x = int(input("Enter x value"))
y = int(input("Enter y value"))
z = x%y
print("The sum of ",x, "and",y, "is",z);

Enter x value10
Enter y value3
The sum of  10 and 3 is 1


## Examples with exponentiation operator

In [17]:
a = 3
b = 2
c = a**b
print(c)

9


In [16]:
x = 4
y = 2
z = x**y
print(z)

16


## Examples with exponentiation operator(using input)

In [18]:
a = int(input("Enter a value"))
b = int(input("Enter b value"))
c = a**b
print("The sum of ",a, "and",b, "is",c);

Enter a value2
Enter b value3
The sum of  2 and 3 is 8


In [19]:
x = int(input("Enter x value"))
y = int(input("Enter y value"))
z = x**y
print("The sum of ",x, "and",y, "is",z);

Enter x value3
Enter y value7
The sum of  3 and 7 is 2187


## Addition, Multiplication, suDivision, Modulo and Exponentiation(all in one)

In [20]:
print(3+6)
print(8-6)
print(3*6)
print(3+6)
print(3+6)

9


## Boolean Expressions

In [11]:
a = 6
b = 7
c = 42
print (1, a == 6)
print (2, a == 7)
print (3, a == 6 and b == 7)
print (4, a == 7 and b == 7)
print (5, not a == 7 and b == 7)
print (6, a == 7 or b == 7)
print (7, a == 7 and b == 6)
print (8, not(a == 7 and b ==6 ))
print (9, not a == 7 and b ==6) 

1 True
2 False
3 True
4 False
5 True
6 True
7 False
8 True
9 False


# Expression result:
### 1. true and true = true
### 2. true and false = false
### 3. false and true = false
### 4. false and false = false

# Expression result:
### 1. not true = false
### 2. not false = true


# Expression result:
### 1. true or true = true
### 2. true or false = true
### 3. false or true = true
### 2. false or false = true


## print function

### is function that print the result in the screen

In [2]:
print('welcome to mr foday computer training school')

welcome to mr foday computer training school


In [3]:
a = 'mr foday was attended at the ahmadiyya muslim secondary school freetown'
print(a)

mr foday was attended at the ahmadiyya muslim secondary school freetown


In [5]:
He_is_mr_foday = True
if He_is_mr_foday:
    print("yes")
else:
    print("He is not mr foday")

yes


## List: is a type of data like strings and integers that we have seen so far, it is use to collect a group of items of an element.

# HOW TO DEFIND A LIST (variable x)

In [17]:
x = [5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100]

#this line means, defind a new list with the element (5 to 100) and asign this list to the variable (x)

In [18]:
print(x)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


## index position: in list, you can access data using index position, the first index is zero, second is one, third is two and so on


In [19]:
print(x[0])
#this means retreved zero index from the list (x) and in python, the first index is zero, second is one, third is two and so on

5


In [20]:
print(x[1])

10


In [11]:
print(x[2])

15

In [12]:
print(x[3])

20

In [13]:
print(x[4])

25

In [14]:
print(x[5])

30

## we can print a range of values

In [23]:
print(x[0:2])

[5, 10]


In [17]:
print(x[0:3])

[5, 10, 15]

In [20]:
print(x[0:4])

[5, 10, 15, 20]

In [24]:
print(x[0:])

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


In [25]:
print(x[1:])

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


In [26]:
print(x[2:5])

[15, 20, 25]


# HOW TO DEFIND A LIST (variable a)

In [1]:
a = [3, 10, -1]
#this line means, defind a new list with the element (3, 10, -1) and asign this list to the variable (a)

In [2]:
print(a)

[3, 10, -1]


# HOW TO ADD AN ITEM IN THE LIST

In [3]:
a. append(1)
#this line means, we add 1 to the list

In [4]:
print(a)

[3, 10, -1, 1]


In [5]:
a.append("hello")
print(a)

[3, 10, -1, 1, 'hello']


In [6]:
a.append([1, 2, 3])
#we can also add a list to another list
#this line means, add this new list to the list (a)
print(a)

[3, 10, -1, 1, 'hello', [1, 2, 3]]


# HOW TO DELETE THE LAST ITEM IN THE LIST

In [7]:
a.pop()
print(a)

[3, 10, -1, 1, 'hello']


In [8]:
a.pop()
print(a)

[3, 10, -1, 1]


# HOW TO RETRIVED A SPECIFIC ITEM FROM THE LIST

In [10]:
print(a[0])
#this means retreved zero index from the list (a) and in python, the first index is zero, second is one, third is two and so on


3


In [11]:
print(a[3])

1


In [12]:
print(a[2])

-1


# HOW TO CHANGE AN ITEM FROM THE LIST

In [15]:
a[0] = 20

In [16]:
print(a)

[20, 10, -1, 1]


In [27]:
c = ["banana", "apple", "orange"]
print(c)

['banana', 'apple', 'orange']


# HOW TO ENTRE CHANGE AN ITEM

In [28]:
temp = c[0]
c[0] = c[2]
c[2] = temp
print(c)

['orange', 'apple', 'banana']


In [29]:
temp = c[1]
c[1] = c[2]
c[2] = temp
print(c)

['orange', 'banana', 'apple']


In [30]:
temp = c[2]
c[2] = c[0]
c[0] = temp
print(c)

['apple', 'banana', 'orange']


# Dictionary in python: As we know dictionary is a place to search for something.

In [34]:
a = {1:'foday', 2:'abu', 3:'sorie', 4:'fatmata'}
a

{1: 'foday', 2: 'abu', 3: 'sorie', 4: 'fatmata'}

In [35]:
##to access data in the dictionary, we call on the key
a[1]

'foday'

In [36]:
a[2]

'abu'

In [37]:
a[3]

'sorie'

In [38]:
a[4]

'fatmata'

In [39]:
a.get(1)

'foday'

In [40]:
a.get(5)
print(a.get(5))

None


In [41]:
a.get(5,'Not Found')

'Not Found'

# HOW TO MATCH TWO VALUES INTO DICTIONARY

In [42]:
keys = ['foday', 'abu', 'sorie', 'fatmata']
values = ['Python','Java','js','Html']
a = dict(zip(keys,values))
a


{'foday': 'Python', 'abu': 'Java', 'sorie': 'js', 'fatmata': 'Html'}

In [45]:
a['foday']

'Python'

# HOW TO ADD A VALUE

In [46]:
a['sudie'] = 'cs'
a

{'foday': 'Python',
 'abu': 'Java',
 'sorie': 'js',
 'fatmata': 'Html',
 'sudie': 'cs'}

# HOW TO DELETE DICTIONARY

In [47]:
del a['sudie']
a

{'foday': 'Python', 'abu': 'Java', 'sorie': 'js', 'fatmata': 'Html'}

# Conditional statement using in loops statement 

In [26]:
nums = ["Lansana","Foday","Alhanssan","Timber","Abubakarr"]

for x in nums:
    print(x)

Lansana
Foday
Alhanssan
Timber
Abubakarr


In [27]:
nums = ["Cow","Goat","Sheep","Dog","Cat"]

for x in nums:
    print(x)

Cow
Goat
Sheep
Dog
Cat


In [28]:
nums = ["Book","Pen","Table","Desk","Eraser"]

for x in nums:
    print(x)

Book
Pen
Table
Desk
Eraser


# Conditional statement using in loops statement 

In [29]:
x = 1
y = 2

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20
2 x 11 = 22
2 x 12 = 24


In [30]:
x = 1
y = 3

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30
3 x 11 = 33
3 x 12 = 36


In [1]:
x = 1
y = 4

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
4 x 11 = 44
4 x 12 = 48


In [1]:
x = 1
y = 5

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
5 x 11 = 55
5 x 12 = 60


In [2]:
x = 1
y = 6

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
6 x 11 = 66
6 x 12 = 72


In [3]:
x = 1
y = 7

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70
7 x 11 = 77
7 x 12 = 84


In [4]:
x = 1
y = 8

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80
8 x 11 = 88
8 x 12 = 96


In [5]:
x = 1
y = 9

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90
9 x 11 = 99
9 x 12 = 108


In [6]:
x = 1
y = 10

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100
10 x 11 = 110
10 x 12 = 120


In [7]:
x = 1
y = 11

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110
11 x 11 = 121
11 x 12 = 132


In [8]:
x = 1
y = 12

while x <= 12:
    print(str(y) + " x " + str(x) + " = " + str(y*x))
    x += 1

12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120
12 x 11 = 132
12 x 12 = 144


# Conditional statement using if statement 

In [2]:
yob = int(input("Enter year of birth:"))
age = 2021 - yob
age_limit = 60
if age >= age_limit:
    print("You are above age requirement.\nYou have dued retirement")

Enter year of birth:12
You are above age requirement.
You have dued retirement


# Conditional statement using if and else statement 

In [4]:
transport = float(input("Enter transport:\n"))

if transport>=10000:
    print("Onboard")
else:
    print("Trek")

Enter transport:
10000
Onboard


In [5]:
transport = float(input("Enter transport:\n"))

if transport>=10000:
    print("Onboard")
else:
    print("Trek")
    

Enter transport:
12
Trek


In [6]:
username = input("Enter username:")
password=input("Enter Password:")

if username=="user" and password=="12345":
    print("Welcome "+username)
else:
    print("Incorrect username or password")

Enter username:foday
Enter Password:077871088
Incorrect username or password


In [7]:
number = int(input("Enter and integer:\n"))

if number%2 == 0 or number%3 == 0:
    print(str(number) + " is either divisible by 2 or 3")
else:
    print(str(number) + " is neither divisible by 2 nor 3")

Enter and integer:
13
13 is neither divisible by 2 nor 3


# Conditional statement using if,elif and else  else statement 

In [8]:
number = int(input("Enter and integer:\n"))

if number%2 == 0:
    print(str(number) + " is divisible by 2")
elif number%3 == 0:
    print(str(number) + " is divisible by 3")
else:
    print(str(number) + " is neither divisible by 2 nor 3")
    

Enter and integer:
23
23 is neither divisible by 2 nor 3


# Numpy and array

In [3]:
import numpy as np
print(np.__version__)

1.20.1


### let started from the basics

In [2]:
#one dimensional array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
 #two dimensional array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
 #three dimensional array
c = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[3.0,2.0,1.0]])
print(c)

[[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [6]:
 #four dimensional array
d = np.array([[12.0,11.0,10.0],[9.0,8.0,7.0],[6.0,5.0,4.0],[3.0,2.0,1.0]])
print(d)

[[12. 11. 10.]
 [ 9.  8.  7.]
 [ 6.  5.  4.]
 [ 3.  2.  1.]]


In [12]:
#Get Dimension
a.ndim

1

In [13]:
#Get shape
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [15]:
c.shape

(3, 3)

In [16]:
#Get type
a.dtype

dtype('int32')

In [17]:
#Get size
a.itemsize

4

In [18]:
#Get size
a.size

3

In [20]:
#Get total size
a.size * a.itemsize

12

In [21]:
#or total size
a.nbytes

12

# Accessing / changing specific elements, rows, columns, etct

In [22]:
x = np. array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
#Geting a specific element in row and column
x[1,4]

12

In [27]:
x[1,-4]

11

In [28]:
#Get a specific row
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
#Get a specific column
x[:,2]

array([ 3, 10])

# CREATING ARRAYS

In [4]:
np.zeros(4)


array([0., 0., 0., 0.])

In [5]:
np.zeros(4).shape

(4,)

In [8]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.zeros((4,5)).shape

(4, 5)

In [17]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# RESHAPING AN ARRAY

In [20]:
g = np.arange(18)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [21]:
g_new = g.reshape(6,3)
print(g_new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [22]:
g_new[1,2] = 100
print(g_new)

[[  0   1   2]
 [  3   4 100]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]
 [ 15  16  17]]


# RESHAPING AN ARRAY IN PROFESSIONAL WAY

In [23]:
g = np.arange(18)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [24]:
g_new2 = g.reshape(-1,3)
print(g_new2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


# Norm

### how to find a Norm

In [32]:
x = np.array ([3,4])
from numpy import linalg
linalg.norm(x)

5.0

# MATRIX MULTIPLICATION

In [33]:
A = np.arange(0,12).reshape(3,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
B = np.ones((4,1))
print(B)

[[1.]
 [1.]
 [1.]
 [1.]]


In [35]:
np.matmul(A,B)

array([[ 6.],
       [22.],
       [38.]])